### ISSUE TITLE
In xcode version 8 , swift 3 , can not change to arabic RTL

### ISSUE THREAD

**Issue by iosworkjo** [MoathOthman/Localization102#1]
Hi 
Hello 
In xcode version 8 , swift 3 , can not change to arabic RTL

Thank you ver much

**Comment by MoathOthman** [comment]
Thanks for mentioning that , I still have not tried it with Swift 3 . 
I will try to fix it ASAP. 
After trying , its harder than I thought and may take some time . :(

**Comment by MoathOthman** [comment]
Now its fixed and pushed , you can find it in Swift3 branch
