### ISSUE TITLE
UILabel center

### ISSUE THREAD

**Issue by r-zgm** [MoathOthman/Localization102#16]
Thank you for this lib.
I have the following issue: 
when activating following line of code
`MethodSwizzleGivenClassName(cls: UILabel.self, originalSelector: #selector(UILabel.layoutSubviews), overrideSelector: #selector(UILabel.cstmlayoutSubviews)) `
from **DoTheMagic** method, then any label with `.textAlignment = .center` will lose its alignment, any help?

**Comment by r-zgm** [comment]
Used https://github.com/MoathOthman/MOLH 
seems to be working fine

**Comment by MoathOthman** [comment]
Great

Sent from my iPhone

On 4 Feb 2021, at 11:15 AM, r-zgm <notifications@github.com> wrote:

﻿

Used https://github.com/MoathOthman/MOLH
seems to be working fine
