### ISSUE TITLE
Localize not force loading wrong on native photos camera and library

### ISSUE THREAD

**Issue by vancucit** [MoathOthman/Localization102#4]
It's working nice on project. But when I call out side project like UIImagePickerController to pick a photo, or capture. 
All content title is key, can't mapping to real value. example: "CHOOSE_PHOTO_BUTTON" ...

iphone 6s, ios 10.1

**Comment by MoathOthman** [comment]
can you provide a screenshot of the actual values and what you are expecting? 
thnx

**Comment by MoathOthman** [comment]
its fixed now , thnx for reporting .
