### ISSUE TITLE
scroll view  RTL 

### ISSUE THREAD

**Issue by sallyahmed** [MoathOthman/Localization102#6]
do you have any idea about scroll view ?

**Comment by MoathOthman** [comment]
wht do u mean?

**Comment by sallyahmed** [comment]
i want to make scroll  swipe gesture from Right to left also

**Comment by MoathOthman** [comment]
you may check if the direction is RTL and change the scrollView inset .

you can add this extension 


```
public extension UIApplication {
    public class func isRTL() -> Bool{
        return UIApplication.shared.userInterfaceLayoutDirection == .rightToLeft
    }
}

```

you can use it something like this 

`if UIApplication.isRTL() {
// scroll to the end of the scrollView 
scroll.contentOffset.x = scroll.contentSize.width
}
`
