### ISSUE TITLE
How to change language of application when click on button?

### ISSUE THREAD

**Issue by mangireddy58** [MoathOthman/Localization102#8]
Hi MoathOthman,
It is possible to change the hole application when click on one button? and one more thing i have multiple Localization. please let me know.

Thnaks.

**Comment by MoathOthman** [comment]
HI Mango ,  yes you can have multiple localization,   am not sure about the first question , you can change the language with one button , ... 
please use https://github.com/MoathOthman/MOLH as it is more advanced and mantained. 
happy coding.

**Comment by mangireddy58** [comment]
Thanks for your quick reply. i will try and let you.

Thank you.

**Comment by pradeep-k-singh** [comment]
Hello MoathOthman,
As my requirement  , 
App have language button on Navbar that is visible to every screen ,User can change their language from current screen and app language should be changes with current screen. As I Trying app move to initial screen .

Please help !

**Comment by MoathOthman** [comment]
@pradeepSinghiO  
The app has to restart from beginning , but you can do some routing in the reset method so after setting the rootViewController you can present the latest view controller. but even though you need to re-initialize it again .
